apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-instance.fullname" . }}-secret
  labels:
    {{- include "odoo-instance.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  admin-password: {{ .Values.secrets.adminPassword | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
  {{- if .Values.minio.enabled }}
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
  {{- end }}
  {{- if eq .Values.dump.storage.type "s3" }}
  s3-access-key: {{ .Values.dump.storage.s3.accessKey | quote }}
  s3-secret-key: {{ .Values.dump.storage.s3.secretKey | quote }}
  {{- else if .Values.minio.enabled }}
  s3-access-key: {{ .Values.minio.rootUser | quote }}
  s3-secret-key: {{ .Values.minio.rootPassword | quote }}
  {{- end }}
