apiVersion: v2
name: odoo-instance
description: Odoo Community or rebranded fork instance for local, test and dev
type: application
version: 0.1.0
appVersion: "17.0"
keywords:
  - odoo
  - erp
  - kodpm
